language: generic

os: linux

services:
- docker

git:
  submodules: false

script:
- docker build -t testbed .
- docker-compose build
- docker-compose up -d
- docker run --rm --net host --pid host --userns host --privileged -v /var/run/docker.sock:/var/run/docker.sock:ro testbed examples/basic_example.py
- docker-compose down
