language: python

if: branch != gh-pages

git:
  submodules: false

jobs:
  include:
    - stage: docs
      if: type != pull_request
      python: 3.8
      script: .travis-scripts/docs.sh
    - stage: docker-test
      services:
      - docker
      script: .travis-scripts/docker_build.sh
    - script: .travis-scripts/docker_basic_example.sh
